Import Required packages

In [6]:
import requests
import os
import pandas as pd

Load facilities data into pandas dataframe

In [7]:
df_facilities = pd.read_excel("./airport_data.xlsx", sheet_name="Facilities")

Then we need to check how our dataset looks like by calling the variable containing the data:

In [9]:
df_facilities

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
0,50009.*A,AIRPORT,'ADK,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS WEST,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y,PADK,SS-SR
1,50016.1*A,AIRPORT,'AKK,3/30/2017,AAL,NONE,AK,ALASKA,KODIAK ISLAND,AK,...,NACO,00:00:00,NACO,00:00:00,NaN,NaN,NaN,Y,PAKH,NaN
2,50017.*A,AIRPORT,'Z13,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,NaN,SEE RMK
3,50017.1*C,SEAPLANE BASE,'KKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
4,50020.*A,AIRPORT,'AKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,PFAK,SS-SR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,50920.12*C,SEAPLANE BASE,'2Y3,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,TIE,CARGO,NaN,NaN,NaN
747,50920.*A,AIRPORT,'YAK,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y-L,PAYA,SS-SR
748,50925.1*A,AIRPORT,'A77,3/30/2017,AAL,NONE,AK,ALASKA,KUSKOKWIM,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
749,50928.*C,SEAPLANE BASE,'78K,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN
750,50990.*A,AIRPORT,'L20,3/30/2017,AAL,NONE,AK,ALASKA,UPPER YUKON,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,NaN,CARGO,Y,NaN,NaN